.TH "Game-Project/App.cs" 3 "Thu Nov 3 2022" "Version 0.1" "Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Game-Project/App.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBApplication\&.App\fP"
.br
.RI "\fBApp\fP extends on the monogame class Game to setup and run the game "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBApplication\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Game Engine from the source code\&.
