.TH "Content_Library.Writer.MapWriter" 3 "Thu Nov 3 2022" "Version 0.1" "Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Content_Library.Writer.MapWriter \- A public class that writes the map that has been imported through the pipeline and write it into binary   

.SH SYNOPSIS
.br
.PP
.PP
Inherits ContentTypeWriter< SerialMap >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override string \fBGetRuntimeType\fP (TargetPlatform targetPlatform)"
.br
.ti -1c
.RI "override string \fBGetRuntimeReader\fP (TargetPlatform targetPlatform)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBWrite\fP (ContentWriter output, \fBSerialMap\fP value)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A public class that writes the map that has been imported through the pipeline and write it into binary  
.PP
Definition at line \fB13\fP of file \fBMapWriter\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override string Content_Library\&.Writer\&.MapWriter\&.GetRuntimeReader (TargetPlatform targetPlatform)"

.PP
Definition at line \fB37\fP of file \fBMapWriter\&.cs\fP\&.
.SS "override string Content_Library\&.Writer\&.MapWriter\&.GetRuntimeType (TargetPlatform targetPlatform)"

.PP
Definition at line \fB36\fP of file \fBMapWriter\&.cs\fP\&.
.SS "override void Content_Library\&.Writer\&.MapWriter\&.Write (ContentWriter output, \fBSerialMap\fP value)\fC [protected]\fP"

.PP
Definition at line \fB15\fP of file \fBMapWriter\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Game Engine from the source code\&.
