.TH "Content_Library.Reader.MapReader" 3 "Thu Nov 3 2022" "Version 0.1" "Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Content_Library.Reader.MapReader
.SH SYNOPSIS
.br
.PP
.PP
Inherits ContentTypeReader< TileMap >\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override \fBTileMap\fP \fBRead\fP (ContentReader input, \fBTileMap\fP existingInstance)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB13\fP of file \fBMapReader\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override \fBTileMap\fP Content_Library\&.Reader\&.MapReader\&.Read (ContentReader input, \fBTileMap\fP existingInstance)\fC [protected]\fP"

.PP
Definition at line \fB15\fP of file \fBMapReader\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Game Engine from the source code\&.
