.TH "Library Directory Reference" 3 "Thu Nov 3 2022" "Version 0.1" "Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Library Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBCamera\fP"
.br
.ti -1c
.RI "directory \fBGraphics\fP"
.br
.ti -1c
.RI "directory \fBMapping\fP"
.br
.ti -1c
.RI "directory \fBobj\fP"
.br
.ti -1c
.RI "directory \fBReaders\fP"
.br
.ti -1c
.RI "directory \fBSerializers\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBStatic\&.cs\fP"
.br
.ti -1c
.RI "file \fBUtil\&.cs\fP"
.br
.in -1c
