.TH "Library/Serializers Directory Reference" 3 "Thu Nov 3 2022" "Version 0.1" "Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Library/Serializers Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBSerialColor\&.cs\fP"
.br
.ti -1c
.RI "file \fBSerialLayer\&.cs\fP"
.br
.ti -1c
.RI "file \fBSerialMap\&.cs\fP"
.br
.ti -1c
.RI "file \fBSerialTileset\&.cs\fP"
.br
.in -1c
