.TH "Library.Serializers.SerialTileset" 3 "Thu Nov 3 2022" "Version 0.1" "Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Library.Serializers.SerialTileset
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBsource\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBcolumns\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBSerialTileset\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int Library\&.Serializers\&.SerialTileset\&.columns\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB14\fP of file \fBSerialTileset\&.cs\fP\&.
.SS "string Library\&.Serializers\&.SerialTileset\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB8\fP of file \fBSerialTileset\&.cs\fP\&.
.SS "string Library\&.Serializers\&.SerialTileset\&.source\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB11\fP of file \fBSerialTileset\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Game Engine from the source code\&.
