.TH "Library.Mapping.TileMap" 3 "Thu Nov 3 2022" "Version 0.1" "Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Library.Mapping.TileMap
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLibrary\&.Mapping\&.AbstractMap< Layer >\fP, and \fBLibrary\&.Graphics\&.IGraphicsComponent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBdraw\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB18\fP of file \fBMap\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Library\&.Mapping\&.TileMap\&.draw ()"

.PP
Implements \fBLibrary\&.Graphics\&.IGraphicsComponent\fP\&.
.PP
Definition at line \fB20\fP of file \fBMap\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Game Engine from the source code\&.
