.TH "Library.Util.Box" 3 "Thu Nov 3 2022" "Version 0.1" "Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Library.Util.Box
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBox\fP (float \fBx1\fP, float \fBy1\fP, float \fBx2\fP, float \fBy2\fP)"
.br
.ti -1c
.RI "\fBBox\fP (Vector2 topLeft, Vector2 bottomRight)"
.br
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.ti -1c
.RI "Rectangle \fBconvertXnaRect\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx1\fP"
.br
.ti -1c
.RI "float \fBx2\fP"
.br
.ti -1c
.RI "float \fBy1\fP"
.br
.ti -1c
.RI "float \fBy2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB13\fP of file \fBUtil\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Library\&.Util\&.Box\&.Box (float x1, float y1, float x2, float y2)"

.PP
Definition at line \fB20\fP of file \fBUtil\&.cs\fP\&.
.SS "Library\&.Util\&.Box\&.Box (Vector2 topLeft, Vector2 bottomRight)"

.PP
Definition at line \fB28\fP of file \fBUtil\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "Rectangle Library\&.Util\&.Box\&.convertXnaRect ()"

.PP
Definition at line \fB41\fP of file \fBUtil\&.cs\fP\&.
.SS "override string Library\&.Util\&.Box\&.ToString ()"

.PP
Definition at line \fB36\fP of file \fBUtil\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float Library\&.Util\&.Box\&.x1"

.PP
Definition at line \fB15\fP of file \fBUtil\&.cs\fP\&.
.SS "float Library\&.Util\&.Box\&.x2"

.PP
Definition at line \fB16\fP of file \fBUtil\&.cs\fP\&.
.SS "float Library\&.Util\&.Box\&.y1"

.PP
Definition at line \fB17\fP of file \fBUtil\&.cs\fP\&.
.SS "float Library\&.Util\&.Box\&.y2"

.PP
Definition at line \fB18\fP of file \fBUtil\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Game Engine from the source code\&.
