.TH "Library.Serializers" 3 "Thu Nov 3 2022" "Version 0.1" "Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Library.Serializers
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSerialColor\fP"
.br
.ti -1c
.RI "class \fBSerialLayer\fP"
.br
.ti -1c
.RI "class \fBSerialMap\fP"
.br
.ti -1c
.RI "class \fBSerialTileset\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Game Engine from the source code\&.
