.TH "Library.Camera" 3 "Thu Nov 3 2022" "Version 0.1" "Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Library.Camera
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBViewport\fP"
.br
.RI "The viewport class defines what space is viewable to the player at a given time\&.  "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Game Engine from the source code\&.
