.TH "Library.Serializers.SerialMap" 3 "Thu Nov 3 2022" "Version 0.1" "Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Library.Serializers.SerialMap
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLibrary\&.Mapping\&.AbstractMap< SerialLayer >\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBTileWidth\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBTileHeight\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBWidth\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBHeight\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBSerialColor\fP \fBBackground\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "List< \fBSerialLayer\fP > \fBLayers\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBSerialMap\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBSerialColor\fP Library\&.Serializers\&.SerialMap\&.Background\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB47\fP of file \fBSerialMap\&.cs\fP\&.
.SS "int Library\&.Serializers\&.SerialMap\&.Height\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB41\fP of file \fBSerialMap\&.cs\fP\&.
.SS "List<\fBSerialLayer\fP> Library\&.Serializers\&.SerialMap\&.Layers\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB62\fP of file \fBSerialMap\&.cs\fP\&.
.SS "string Library\&.Serializers\&.SerialMap\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB13\fP of file \fBSerialMap\&.cs\fP\&.
.SS "int Library\&.Serializers\&.SerialMap\&.TileHeight\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB27\fP of file \fBSerialMap\&.cs\fP\&.
.SS "int Library\&.Serializers\&.SerialMap\&.TileWidth\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB20\fP of file \fBSerialMap\&.cs\fP\&.
.SS "int Library\&.Serializers\&.SerialMap\&.Width\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB34\fP of file \fBSerialMap\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Game Engine from the source code\&.
