.TH "Library/Graphics/Renderer.cs" 3 "Thu Nov 3 2022" "Version 0.1" "Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Library/Graphics/Renderer.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLibrary\&.Graphics\&.Renderer\fP"
.br
.RI "Defines whats being rendered and draws it in the screen  "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLibrary\fP"
.br
.ti -1c
.RI "namespace \fBLibrary\&.Graphics\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Game Engine from the source code\&.
