.TH "Library/obj/Debug/net6.0/.NETCoreApp,Version=v6.0.AssemblyAttributes.cs" 3 "Thu Nov 3 2022" "Version 0.1" "Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Library/obj/Debug/net6.0/.NETCoreApp,Version=v6.0.AssemblyAttributes.cs
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Game Engine from the source code\&.
