.TH "Library/Mapping Directory Reference" 3 "Thu Nov 3 2022" "Version 0.1" "Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Library/Mapping Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBLayer\&.cs\fP"
.br
.ti -1c
.RI "file \fBMap\&.cs\fP"
.br
.ti -1c
.RI "file \fBMappingPos\&.cs\fP"
.br
.in -1c
