.TH "Library.Graphics.IGraphicsComponent" 3 "Thu Nov 3 2022" "Version 0.1" "Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Library.Graphics.IGraphicsComponent \- Generic graphics component interface   

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLibrary\&.Graphics\&.GraphicsComponent\fP, \fBLibrary\&.Graphics\&.Renderer\fP, \fBLibrary\&.Mapping\&.Layer\fP, and \fBLibrary\&.Mapping\&.TileMap\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBdraw\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Generic graphics component interface  
.PP
Definition at line \fB8\fP of file \fBGraphicsComponent\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Library\&.Graphics\&.IGraphicsComponent\&.draw ()"

.PP
Implemented in \fBLibrary\&.Graphics\&.GraphicsComponent\fP, \fBLibrary\&.Graphics\&.Renderer\fP, \fBLibrary\&.Graphics\&.Tile\fP, \fBLibrary\&.Mapping\&.Layer\fP, and \fBLibrary\&.Mapping\&.TileMap\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Game Engine from the source code\&.
