.TH "Library.Graphics" 3 "Thu Nov 3 2022" "Version 0.1" "Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Library.Graphics
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGraphicsComponent\fP"
.br
.RI "Generic graphics component abstract class  "
.ti -1c
.RI "interface \fBIGraphicsComponent\fP"
.br
.RI "Generic graphics component interface  "
.ti -1c
.RI "class \fBRenderer\fP"
.br
.RI "Defines whats being rendered and draws it in the screen  "
.ti -1c
.RI "class \fBSprite\fP"
.br
.RI "\fBSprite\fP class defines a sprites texure and hitbox  "
.ti -1c
.RI "class \fBTile\fP"
.br
.RI "A graphics component that represents a map tile  "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Game Engine from the source code\&.
