.TH "Library.Graphics.Renderer" 3 "Thu Nov 3 2022" "Version 0.1" "Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Library.Graphics.Renderer \- Defines whats being rendered and draws it in the screen   

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLibrary\&.Graphics\&.IGraphicsComponent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRenderer\fP (Game game)"
.br
.ti -1c
.RI "void \fBdraw\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines whats being rendered and draws it in the screen  
.PP
Definition at line \fB9\fP of file \fBRenderer\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Library\&.Graphics\&.Renderer\&.Renderer (Game game)"

.PP
Definition at line \fB13\fP of file \fBRenderer\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Library\&.Graphics\&.Renderer\&.draw ()"

.PP
Implements \fBLibrary\&.Graphics\&.IGraphicsComponent\fP\&.
.PP
Definition at line \fB18\fP of file \fBRenderer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Game Engine from the source code\&.
