.TH "Library.Graphics.Tile" 3 "Thu Nov 3 2022" "Version 0.1" "Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Library.Graphics.Tile \- A graphics component that represents a map tile   

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLibrary\&.Graphics\&.GraphicsComponent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTile\fP (\fBSprite\fP \fBsprite\fP, \fBMappingPos\fP \fBposition\fP, Vector2 \fBtileSize\fP, int \fBcolumns\fP, int \fBtileNum\fP)"
.br
.ti -1c
.RI "override void \fBdraw\fP ()"
.br
.RI "Draw the graphics component  "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Vector2 \fBtileSize\fP"
.br
.ti -1c
.RI "\fBMappingPos\fP \fBposition\fP"
.br
.ti -1c
.RI "int \fBtileNum\fP"
.br
.ti -1c
.RI "int \fBcolumns\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A graphics component that represents a map tile  
.PP
Definition at line \fB12\fP of file \fBTile\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Library\&.Graphics\&.Tile\&.Tile (\fBSprite\fP sprite, \fBMappingPos\fP position, Vector2 tileSize, int columns, int tileNum)"

.PP
Definition at line \fB19\fP of file \fBTile\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Library\&.Graphics\&.Tile\&.draw ()\fC [virtual]\fP"

.PP
Draw the graphics component  
.PP
Implements \fBLibrary\&.Graphics\&.GraphicsComponent\fP\&.
.PP
Definition at line \fB28\fP of file \fBTile\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Library\&.Graphics\&.Tile\&.columns"

.PP
Definition at line \fB17\fP of file \fBTile\&.cs\fP\&.
.SS "\fBMappingPos\fP Library\&.Graphics\&.Tile\&.position"

.PP
Definition at line \fB15\fP of file \fBTile\&.cs\fP\&.
.SS "int Library\&.Graphics\&.Tile\&.tileNum"

.PP
Definition at line \fB16\fP of file \fBTile\&.cs\fP\&.
.SS "Vector2 Library\&.Graphics\&.Tile\&.tileSize"

.PP
Definition at line \fB14\fP of file \fBTile\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Game Engine from the source code\&.
