.TH "Library.Mapping.AbstractLayer< T >" 3 "Thu Nov 3 2022" "Version 0.1" "Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Library.Mapping.AbstractLayer< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "int \fBdepth\fP"
.br
.ti -1c
.RI "T \fBtiles\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBLayer\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int \fBLibrary\&.Mapping\&.AbstractLayer\fP< T >\&.depth"

.PP
Definition at line \fB11\fP of file \fBLayer\&.cs\fP\&.
.SS "string \fBLibrary\&.Mapping\&.AbstractLayer\fP< T >\&.name"

.PP
Definition at line \fB10\fP of file \fBLayer\&.cs\fP\&.
.SS "T \fBLibrary\&.Mapping\&.AbstractLayer\fP< T >\&.tiles"

.PP
Definition at line \fB12\fP of file \fBLayer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Game Engine from the source code\&.
