.TH "Library.Mapping.Layer" 3 "Thu Nov 3 2022" "Version 0.1" "Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Library.Mapping.Layer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLibrary\&.Mapping\&.AbstractLayer< List< Tile > >\fP, IComparable< Layer >, and \fBLibrary\&.Graphics\&.IGraphicsComponent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBCompareTo\fP (\fBLayer\fP other)"
.br
.ti -1c
.RI "void \fBdraw\fP ()"
.br
.ti -1c
.RI "int \fBgetDepth\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB15\fP of file \fBLayer\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "int Library\&.Mapping\&.Layer\&.CompareTo (\fBLayer\fP other)"

.PP
Definition at line \fB17\fP of file \fBLayer\&.cs\fP\&.
.SS "void Library\&.Mapping\&.Layer\&.draw ()"

.PP
Implements \fBLibrary\&.Graphics\&.IGraphicsComponent\fP\&.
.PP
Definition at line \fB25\fP of file \fBLayer\&.cs\fP\&.
.SS "int Library\&.Mapping\&.Layer\&.getDepth ()"

.PP
Definition at line \fB36\fP of file \fBLayer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Game Engine from the source code\&.
