.TH "Library.Mapping.MappingPos" 3 "Thu Nov 3 2022" "Version 0.1" "Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Library.Mapping.MappingPos
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMappingPos\fP ()"
.br
.ti -1c
.RI "\fBMappingPos\fP (int x, int y)"
.br
.ti -1c
.RI "\fBMappingPos\fP (int constant)"
.br
.ti -1c
.RI "Vector2 \fBconvertToCoord\fP (Vector2 tileSize)"
.br
.ti -1c
.RI "\fBMappingPos\fP \fBadd\fP (\fBMappingPos\fP p2)"
.br
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBX\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBY\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBMappingPos\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Library\&.Mapping\&.MappingPos\&.MappingPos ()"

.PP
Definition at line \fB12\fP of file \fBMappingPos\&.cs\fP\&.
.SS "Library\&.Mapping\&.MappingPos\&.MappingPos (int x, int y)"

.PP
Definition at line \fB18\fP of file \fBMappingPos\&.cs\fP\&.
.SS "Library\&.Mapping\&.MappingPos\&.MappingPos (int constant)"

.PP
Definition at line \fB24\fP of file \fBMappingPos\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBMappingPos\fP Library\&.Mapping\&.MappingPos\&.add (\fBMappingPos\fP p2)"

.PP
Definition at line \fB35\fP of file \fBMappingPos\&.cs\fP\&.
.SS "Vector2 Library\&.Mapping\&.MappingPos\&.convertToCoord (Vector2 tileSize)"

.PP
Definition at line \fB30\fP of file \fBMappingPos\&.cs\fP\&.
.SS "override string Library\&.Mapping\&.MappingPos\&.ToString ()"

.PP
Definition at line \fB37\fP of file \fBMappingPos\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int Library\&.Mapping\&.MappingPos\&.X\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB9\fP of file \fBMappingPos\&.cs\fP\&.
.SS "int Library\&.Mapping\&.MappingPos\&.Y\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB10\fP of file \fBMappingPos\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Game Engine from the source code\&.
