.TH "Library.Serializers.SerialLayer" 3 "Thu Nov 3 2022" "Version 0.1" "Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Library.Serializers.SerialLayer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLibrary\&.Mapping\&.AbstractLayer< string >\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBDepth\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBSerialTileset\fP \fBTileset\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBData\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBSerialLayer\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string Library\&.Serializers\&.SerialLayer\&.Data\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB28\fP of file \fBSerialLayer\&.cs\fP\&.
.SS "int Library\&.Serializers\&.SerialLayer\&.Depth\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB18\fP of file \fBSerialLayer\&.cs\fP\&.
.SS "string Library\&.Serializers\&.SerialLayer\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB11\fP of file \fBSerialLayer\&.cs\fP\&.
.SS "\fBSerialTileset\fP Library\&.Serializers\&.SerialLayer\&.Tileset\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB25\fP of file \fBSerialLayer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Game Engine from the source code\&.
