.TH "Content Pipeline/Writer/MapWriter.cs" 3 "Thu Nov 3 2022" "Version 0.1" "Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Content Pipeline/Writer/MapWriter.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBContent_Library\&.Writer\&.MapWriter\fP"
.br
.RI "A public class that writes the map that has been imported through the pipeline and write it into binary  "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBContent_Library\fP"
.br
.ti -1c
.RI "namespace \fBContent_Library\&.Writer\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Game Engine from the source code\&.
